version: '3.7'


services:

  web:

    build: .

    command: gunicorn blue_sun_site.wsgi -b 0.0.0.0:8000

    volumes:

      - .:/code

    ports:

      - 8000:8000

    depends_on:

      - db

  db:

    image: postgres:11

    env_file: database.env

    volumes:

      - postgres_data:/var/lib/postgresql/data/


volumes:

  postgres_data: